# get insights
POST http://localhost:7777/api/insights/getInsights
Content-Type: application/json

{
    "startDate" :"12-12-2020",
    "endDate":"12-15-2020", 
    "category": "sports",
    "customQuery": "tennis"
}