# get insights
POST http://localhost:7777/api/insights/getInsights
Content-Type: application/json

{
    "startDate" :"2022-03-01",
    "endDate":"2022-03-10"
    # "customQuery":"war",
    # "category": "war"
}